//

export type ImageKey = keyof typeof Images;

export const Images = {
  abeja: require('./abeja.png'),
  ala: require('./ala.png'),
  angel: require('./angel.png'),
  anillo: require('./anillo.png'),
  araña: require('./araña.png'),
  arbol: require('./arbol.png'),
  arco: require('./arco.png'),
  ardilla: require('./ardilla.png'),
  aro: require('./aro.png'),
  asno: require('./asno.png'),
  ave: require('./ave.png'),
  avion: require('./avion.png'),
  barco: require('./barco.png'),
  campana: require('./campana.png'),
  casa: require('./casa.png'),
  conejo: require('./conejo.png'),
  cuna: require('./cuna.png'),
  edificio: require('./edificio.png'),
  elefante: require('./elefante.png'),
  empanada: require('./empanada.png'),
  enano: require('./enano.png'),
  enchufe: require('./enchufe.png'),
  erizo: require('./erizo.png'),
  escalera: require('./escalera.png'),
  escoba: require('./escoba.png'),
  espada: require('./espada.png'),
  espejo: require('./espejo.png'),
  esposas: require('./esposas.png'),
  esquimal: require('./esquimal.png'),
  estrella: require('./estrella.png'),
  estufa: require('./estufa.png'),
  gato: require('./gato.png'),
  gato_2: require('./gato_2.png'),
  iglesia: require('./iglesia.png'),
  iglu: require('./iglu.png'),
  iguana: require('./iguana.png'),
  iman: require('./iman.png'),
  insecto: require('./insecto.png'),
  isla: require('./isla.png'),
  luna: require('./luna.png'),
  manzana: require('./manzana.png'),
  martillo: require('./martillo.png'),
  ojo: require('./ojo.png'),
  ola: require('./ola.png'),
  olla: require('./olla.png'),
  oreja: require('./oreja.png'),
  oruga: require('./oruga.png'),
  oso: require('./oso.png'),
  oveja: require('./oveja.png'),
  ovillo: require('./ovillo.png'),
  pato: require('./pato.png'),
  plato: require('./plato.png'),
  taza: require('./taza.png'),
  uña: require('./uña.png'),
  unicornio: require('./unicornio.png'),
  utiles: require('./utiles.png'),
  uva: require('./uva.png'),
  zapato: require('./zapato.png'),
  logo_1: require('./logo_1.png'),
  logo_2: require('./logo_2.png'),
  logo_3: require('./logo_3.png'),
} as const;
