//

export type ImageKey = keyof typeof Images;

export const Images = {
  abeja: require('./abeja.png'),
  ala: require('./ala.png'),
  anillo: require('./anillo.png'),
  araña: require('./araña.png'),
  arbol: require('./arbol.png'),
  arco: require('./arco.png'),
  ardilla: require('./ardilla.png'),
  aro: require('./aro.png'),
  ave: require('./ave.png'),
  avion: require('./avion.png'),
  barco: require('./barco.png'),
  campana: require('./campana.png'),
  conejo: require('./conejo.png'),
  cuna: require('./cuna.png'),
  elefante: require('./elefante.png'),
  empanada: require('./empanada.png'),
  enano: require('./enano.png'),
  erizo: require('./erizo.png'),
  escoba: require('./escoba.png'),
  espada: require('./espada.png'),
  estrella: require('./estrella.png'),
  gato: require('./gato.png'),
  gato_2: require('./gato_2.png'),
  iguana: require('./iguana.png'),
  manzana: require('./manzana.png'),
  martillo: require('./martillo.png'),
  oso: require('./oso.png'),
  pato: require('./pato.png'),
  uva: require('./uva.png'),
  logo_1: require('./logo_1.png'),
  logo_2: require('./logo_2.png'),
  logo_3: require('./logo_3.png'),
} as const;
